spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce_user
spring.datasource.password=160322057@Busayo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver